### ISSUE TITLE
Only 1st LED shows Print progress

### ISSUE THREAD

**Issue by NeKoMuck** [EricHigdon/OctoPrint-RGB_status#12]
While using the Print Progress Function, only the first LED of my strip is changing the colour. All other 59 LED still using the base color.

All other Functions of the Plugin seems to be working.

**Comment by EricHigdon** [comment]
@nekomuck can you please share your OctoPrint.log file?

**Comment by NeKoMuck** [comment]
@EricHigdon Here it is...

[octoprint.log](https://github.com/EricHigdon/OctoPrint-RGB_status/files/2972508/octoprint.log)

**Comment by NeKoMuck** [comment]
I'am using a WS2812B Stripe. LED type is set to WS2812, because there is no WS2812B option in your plugin. Maybe this is the problem ?

The octoprint.log seems to count more than the 60 LEDs, i have set. Is that correct ?

I have made a complete new installation of Octoprint and RGB Status, but the problem is still available.

**Comment by EricHigdon** [comment]
Ws2812 should be fine. If the other effects are working, that’s certainly not the problem. 

I’d guess it’s a problem with my algorithm. You have 60 leds? What happens if you set the number of leds to 10 in the settings?

**Comment by EricHigdon** [comment]
I've confirmed that this is not working properly for larger numbers of LEDs.

**Comment by NeKoMuck** [comment]
Thank you for your Feedback. Good to know, its not my fault.
I hope you will find the problem. I appreciate your plugin.

Using only 10 LED works perfect:

![IMG-3218](https://user-images.githubusercontent.com/48601195/54481422-ada0b300-4834-11e9-8704-ea3803fbb6f8.JPG)

![IMG-3224](https://user-images.githubusercontent.com/48601195/54481913-7386df80-483b-11e9-9876-d23d2ba43c48.JPG)

**Comment by EricHigdon** [comment]
This should be fixed with 7cfe918. Once I’ve done some more testing, I’ll release.

**Comment by NeKoMuck** [comment]
It would be great, when the LED turn off after a (self)defined time, when the Job has finished.

**Comment by EricHigdon** [comment]
@NeKoMuck when the print completes, the leds go back to the idle effect, so you could accomplish something like that by setting the idle effect to a solid color and the color to black.

**Comment by NeKoMuck** [comment]
I set the idle color to solid black, but the LED still shining green. I will try it again tomorrow.

![idle effect color](https://user-images.githubusercontent.com/48601195/54482263-23ab1700-4841-11e9-82f6-a5e53b5aca91.png)

**Comment by EricHigdon** [comment]
Fixed in 7cfe918

@NeKoMuck If you confirm that when your print is finished, the idle effect does not start, please open a new issue.
