### ISSUE TITLE
LED won´t go in idle Mode

### ISSUE THREAD

**Issue by NeKoMuck** [EricHigdon/OctoPrint-RGB_status#15]
When print has finished and the last LED switches to the correct progress color, all LED going off for some milliseconds and then still shining in the progress color. 

[octoprint.log](https://github.com/EricHigdon/OctoPrint-RGB_status/files/2975410/octoprint.log)

In logfile see lines 3307 - 3322

When Octoprint switches in line 3320 from "Finishing" to "Operational" the solid color will be killed.
What does the error in Line 3311 mean ? Is this a problem with your plugin ?

Here a link to the video showing the last seconds of printing:

https://streamable.com/5uqhr

**Comment by EricHigdon** [comment]
The error on 3311 is not related. It's a known issue with the tracking plugin if you have usage tracking disabled (see [here](https://github.com/foosel/OctoPrint/issues/2967)).

Lines 3309–3310 indicate that it changed to your idle effect after the 99% progress call.
Then on lines 3321–3322 it changed to 100% progress bar.

This means that OctoPrint actually triggered the PrintComplete hook before triggering the on_progress(100) hook. You have the same version of OctoPrint that I do, and I've not experienced this. I'll have to dig into this further.

**Comment by EricHigdon** [comment]
Should be fixed with a0bdf7d05e497f7a065cc5c62dc5c966c05af022
