### ISSUE TITLE
Please show a video and pictures of this project in action

### ISSUE THREAD

**Issue by madmax2** [EricHigdon/OctoPrint-RGB_status#17]
Would be good if you can provide a video and pictures of this plugin running so we can see how it works.

Also as a side note
what is the benefit of the having RGB status indicators vs just looking at the LCD screen or octoprint terminal message?
Maybe adding some more info about the project benefits would be good..

And what does the different color indicators signal?
Please update the info page so we can understand what would each of the colors signal and if there is any flashing of colors means?

**Comment by EricHigdon** [comment]
@madmax2 You're right. That would be cool. Once I get as many of the bugs worked out as I can, I might try to make a video.

To answer your side note question: It's cooler. JK (kind of), The LEDs are more visible from a distance, and you don't have to be logged in to the terminal to check the progress.

There are various effects available for various states of OctoPrint. You can choose which effect to use when, and which colors to use for the progress bar.
