### ISSUE TITLE
[REQUEST] Ability to call a script at various points

### ISSUE THREAD

**Issue by frakman1** [EricHigdon/OctoPrint-RGB_status#18]
This is a great plugin to directly control a wired LED strip. It looks like it lets you select certain colors for certain stages of a print (startup, idle, progress)

It would be great if you could add the option to call  a script (or anything you can type at the terminal). This would allow for other devices to be controlled (WiFi Lights, Audio Speakers etc)
It would just be a string a parameter for each stage.

**Comment by EricHigdon** [comment]
This can already be done with the built-in[ OctoPrint Events system](http://docs.octoprint.org/en/master/events/index.html).

**Comment by frakman1** [comment]
Thank you so much for this link!
