### ISSUE TITLE
Cannot instal

### ISSUE THREAD

**Issue by Penfold81** [EricHigdon/OctoPrint-RGB_status#2]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-2fSZRe/
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

Octoprint Version 1.3.10

Octopi Version 0.15.1, running on Raspberry Pi 3 Model B Plus Rev 1.3

**Comment by EricHigdon** [comment]
Fixed with b69b558e2087af5b3cc542d590f9ed234fd9e33a
