### ISSUE TITLE
Random Flicker

### ISSUE THREAD

**Issue by RootUser3885** [EricHigdon/OctoPrint-RGB_status#21]
Now that I got them working with the frequency fix, the LEDs will randomly flicker. It only flashes for an instant but enough to be annoying. Sometimes random LEDs are different colors than they should be. The flicker is rather spaced out, sometimes ever 5 mins, or up to 30 mins, making it hard to catch on video. Im using WS2812b strips of 72.
[octoprint .log](https://github.com/EricHigdon/OctoPrint-RGB_status/files/3078362/octoprint.log)
![Screenshot (1)](https://user-images.githubusercontent.com/40777042/56106849-bbffee80-5f08-11e9-9924-d1d5a61832da.png)
![Screenshot (2)](https://user-images.githubusercontent.com/40777042/56106856-c621ed00-5f08-11e9-9ac8-a4f7155c3749.png)

**Comment by EricHigdon** [comment]
Interesting. Did you also set your max buffer size? See https://github.com/jgarff/rpi_ws281x#spi

**Comment by JohnTRoth** [comment]
I also have this on occasion. I do have my buffer size set appropriately - but suspect it's actually interference with the cable between the RGB strip and the Pi. Moving to a better cable improved things but didn't totally eliminate the issue. Next step is to shorten the length.

**Comment by EricHigdon** [comment]
@JohnTRoth, yes. Cable length can be a problem, because the LEDs work on a 5v signal, but the RaspberryPi only outputs a 3.3v signal. A shorter cable and/or a level shifter is probably necessary.
