### ISSUE TITLE
Hardware revision not supported

### ISSUE THREAD

**Issue by abkawula** [EricHigdon/OctoPrint-RGB_status#26]
I'm running this on a pi 4 and am getting the following log message (as well as nothing working):

`2019-07-30 02:56:43,198 - octoprint.plugins.rgb_status - ERROR - ws2811_init failed with code -3 (Hardware revision is not supported)`

**Comment by EricHigdon** [comment]
@abkawula I have acquired a raspberry pi 4, but have not even gotten around to taking it out of the box yet. I'll have a look at this eventually, but it may take a while—sorry!

That said, I think this issue will have to be fixed by the maintainers of https://github.com/jgarff/rpi_ws281x
