### ISSUE TITLE
Setup Wizard appears every time i visit the Octoprint page

### ISSUE THREAD

**Issue by cs2000** [EricHigdon/OctoPrint-RGB_status#32]
Not sure if this one is just me or... but since upgrading recently to the new RGB Status version that has the rather nice setup wizard, i cant seem to get it to go away!

I performed all the steps it wanted me to, and have green ticks by them all, but every time i access the Octoprint admin page, the setup wizard comes back up again. Its still all green ticks, i just have to press finish and it goes away, 

Its just rather annoying it does this at every login.

**Comment by EricHigdon** [comment]
Interesting. OctoPrint is supposed to be handling the hiding of the wizard if you’ve already completed it, I’ll have a look.

**Comment by cs2000** [comment]
Appreciate it, if you need any logs etc, let me know, happy to provide.

**Comment by EricHigdon** [comment]
I think this is a bug in the current version of OctoPrint (1.3.11). It will be fixed in 1.3.12, but until then, you should be able to fix it by holding shift while clicking the refresh button in your browser. 
https://github.com/foosel/OctoPrint/issues/3211
