### ISSUE TITLE
GRBW richtig anschließen

### ISSUE THREAD

**Issue by matzepfaff** [EricHigdon/OctoPrint-RGB_status#39]
Hallo zusammen,

ich steh aufm Schlauch. Ich habe einen GRBW-Streifen. Aber wo kommt jetzt welcher PIN bei den GPIO hin? Das schwarze Kabel kommt auf die +12V. Aber die Farben GRBW kommen an welche Pin's? 

Danke für Eure Hilfe
Matze

**Comment by EricHigdon** [comment]
It sounds like you may have a “dumb” led strip. This plugin currently only supports “smart” strips that are individually addressable.
