### ISSUE TITLE
Ability to 'reserve' LEDs wired in series for distinct behaviour

### ISSUE THREAD

**Issue by drewzh** [EricHigdon/OctoPrint-RGB_status#49]
Use case: To have an additional X LEDs wired in series, reserved for certain statuses, such as probing or errors scenarios etc, but default to white at other times (or even for starters, to be reversed for just white at all times and not be affected by neighbouring effects).

I have a bar of LEDs across the top of the printer and it would be nice to be able to wire in series, an extra for e.g, 3 LEDs and run these down to the hotend, to provide a set of distinct LEDs that can be always white (or set to other colours to show hotend status etc).

I have a feeling that this might be covered by the idea of having 'LED groups' but I'm not sure at a technical level whether this is doable, so I wanted to create a more simplistic approach if this an easier solution in the interim.

Thanks again for the great plugin!

**Comment by EricHigdon** [comment]
This is for sure going to be covered by #10. This is actually the primary way that I would use the LED groups. That way I could have a heating effect on a single LED that I want to mount on the hot end.
