### ISSUE TITLE
RPI4: LEDs stay white most of the time

### ISSUE THREAD

**Issue by Gifford47** [EricHigdon/OctoPrint-RGB_status#54]
This was the first issue:
[#16 ](https://github.com/EricHigdon/OctoPrint-RGB_status/issues/16#issue-423065547)

the same problem appears to occur again with rpi4. i have now set core_freq=500 for me, but no change, the leds glow white all the time. any advice?

**Comment by EricHigdon** [comment]
Try adding enable_uart=1 to config.txt

**Comment by Gifford47** [comment]
great, thanks a lot! it works!
but after shutting down octoprint the leds change to white and stay on... thats another problem
