### ISSUE TITLE
Raspberry 4 rgb status problem

### ISSUE THREAD

**Issue by valurian** [EricHigdon/OctoPrint-RGB_status#61]
I have a Raspberry 4 with Octoprint and I want to use some plugins (RGB Status) to handle a strip of 26 LEDs ws2812B.

 I connect the power to the Raspberry (in the future to a power supply) and the Din cable from the strip to pin 19 gpio 10 as indicated by the plugin.

 I have activated SPI in sudo raspi-config
 And user Pi
 I checked the core_freq and it is at 250

 The strip lights up white and when I send it an order to change it, it changes to the indicated color for two seconds and returns to white.

 From what I have read there are problems with this board and the leds someone knows some solution.

 I have followed the advice in this thread.

 https://community.octoprint.org/t/rgb-status-ws2812b/8534/24

 And from the author's repository, which says that version 1.6 (the one I use) has already corrected the compatibility problems but it still fails.

 Help!!  Thank you so much everyone!

**Comment by EricHigdon** [comment]
See #54
