### ISSUE TITLE
Sleep / Night Lighting Mode

### ISSUE THREAD

**Issue by johnrbussard** [EricHigdon/OctoPrint-RGB_status#67]
Hello,

I have my printer in the same room as I sleep, and currently manually reset the led brightness.  It would be nice if there was a way to macro this, perhaps in the top bar of Octoprint.  I think it would be great if there could be instant overrides for 'off, night, bright white' without having to edit and redit the settings.  Thanks for your consideration!

**Comment by EricHigdon** [comment]
I think #46 covers this? If not, it will probably be part of #51
