### ISSUE TITLE
Neopixel with level shifter on pin 21 not working

### ISSUE THREAD

**Issue by p8ght** [EricHigdon/OctoPrint-RGB_status#69]
I am running Neopixels on Pin 21 (BCM21) using a level shifter.
When starting octoprint with root ( ./octoprint --iknowwhatimdoing ) following shows up:

```
- octoprint.plugins.rgb_status - ERROR - ws2811_init failed with code -5 (mmap() failed)
- octoprint.plugins.rgb_status - ERROR - Error running effect: The strip object does not exist. Did it 
   fail to initialize?
- octoprint.plugins.rgb_status - INFO - Starting Disconnected Effect
- octoprint.plugins.rgb_status - ERROR - Error running effect: The strip object does not exist. Did it 
   fail to initialize?
```
-> Neopixels don't light up at all

(i am using a touchscreen which is using pin10 - spi)

**Comment by Hasinator** [comment]
Figured it out: didn't run octoprint as root correctly
`[https://community.octoprint.org/t/gpio10-already-used-run-octoprint-as-root-how/20351/6?u=hasinator](url)`

**Comment by p8ght** [comment]
I didn't run octoprint as root correctly
[https://community.octoprint.org/t/gpio10-already-used-run-octoprint-as-root-how/20351/6?u=hasinator](url)
