### ISSUE TITLE
1.7.0 Thoughts

### ISSUE THREAD

**Issue by cp2004** [EricHigdon/OctoPrint-RGB_status#71]
Not really an 'issue' as such, but as you said in #65 I'll give you my findings from my initial testing:
- It works 👍
- Restarting works 👍 
- On my pi with an Octoprint dev environment set up, the LEDs work. However, on my OctoPi that is attached to the printer nothing is showing up on the LEDs. It could be settings or something but as far as I can see they are the same
- The strip is generally slow to respond: Could just be waiting for effect process to spin up/down. I have a few ideas that I was working on before you released 1.7 to fix the issues, and at the moment I think it responds faster. If I can finish it I'll ping you so you can have a look
Looking through the code, it is getting more complicated! I was thinking it could be a little simpler but if it works...

**Comment by cp2004** [comment]
The only difference is that the printer is running Python 2, and my dev Python 3. I'll test if it is Python 3 vs 2 in a minute

EDIT: Yep, it's Python 2. So now the plugin is only Python 3 compatible?

**Comment by EricHigdon** [comment]
Ok, so something is up with python 2 now. I thoroughly tested both versions. The only thing I can think of is that maybe running python 2.7 on startup causes an issue. I’m currently provisioning an additional RaspberryPi with a fresh OctoPrint install to try to track down the issue.

**Comment by cp2004** [comment]
I've just managed to get it to work. Nothing was showing in logs for RGB_Status for python 2 but after a couple of restarts on the dev pi it worked. No idea!

Edit: Now I can't get it to not work on the dev pi, but that doesn't help my OctoPi. I'll look into it tomorrow, it could be my setup if no one else reports it.

One final note is that now the plugin is Py3 compatible, you need to update the repo to add the flag, just so people know.

**Comment by cp2004** [comment]
@EricHigdon thank you so much for your work on this, just updated the Printer to 1.7.1 and it worked beautifully. Ping me if you need any more testing or help for new features!
