### ISSUE TITLE
Can't upgrade from 1.6.0 to 1.7.1

### ISSUE THREAD

**Issue by orgalinq** [EricHigdon/OctoPrint-RGB_status#72]
Hello,
Yesterday successfully upgraded from 1.6.0 to 1.7.1. (Os: PI  Buster)
Today, on another PI & printer, I can't upgrade. (Os: PI  Stretch)
I get error codes, see my Logs. 
Can you help me to fix this?

[RGB install error logs.txt](https://github.com/EricHigdon/OctoPrint-RGB_status/files/4789101/RGB.install.error.logs.txt)

Thank You very much in advance.

**Comment by cs2000** [comment]
I too am getting this issue, even tried removing the plugin, rebooting and reinstalling, same error messages as the above commenter.

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-2ZACPx/
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output`

**Comment by wees** [comment]
Also having the same error when trying to update:

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-y0tfxp/`

**Comment by EricHigdon** [comment]
Can someone try updating again? I think I have this issue resolved. in V1.7.2.

**Comment by cs2000** [comment]
Worked first time for me this time around. Thanks for the fix!
